version: "2.2"

services:
  petclinic:
    image: srikp/images:petclinic_img
    container_name: petclinic
    ports:
      - 9072:8080
    depends_on:
      - postgres  
    restart: always
  postgres:
    image: postgres:15.3
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    profiles:
    - postgres
