petclinic:
  build:
    context: .
    dockerfile: Dockerfile
  ports:
    - "8081:8080"
  depends_on:
    - postgres
  command: ["./wait-for-it.sh", "postgres:5432", "--", "java", "-jar", "spring-petclinic-3.1.0-SNAPSHOT.jar", "--spring.profiles.active=postgres"]
  networks:
    - app-network
