
version: "2.2"

services:
  petclinic:
    image: srikp/images:petclinic_img
    container_name: petclinic
    ports:
      - 8088:8080
    depends_on:
      - postgresql  
    restart: always
  postgresql:
    image: postgres:15.3
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    profiles:
    - postgres
