version: '3'
services:
  postgres:
    image: postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/petclinic
      POSTGRES_USER: petclinic
      POSTGRES_PASSWORD: petclinic
      POSTGRES_DB: petclinic
    volumes:
      - postgres_data:/var/lib/postgresql/data

  petclinic:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    volumes:
      - petclinic_data:/app/data

volumes:
  postgres_data:
  petclinic_data:
