version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: petclinic
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: petclinic
    ports:
      - "5432:5432"
    networks:
      - app-network

  petclinic:
    image: srikp/images:petclinic_img
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
