version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: petclinic
      POSTGRES_PASSWORD: petclinic
      POSTGRES_DB: petclinic

  petclinic:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - postgres
