name: BuildDockerImage

on:
  workflow_run:
    workflows: ["BuildPetclinicApp"]
    types:
      - completed

jobs:
  BuildDockerImage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Build the Docker image
        run: |
          ls target
          cd target
          pwd
          
          docker build . --file Dockerfile --tag petclinic:latest
