name: Petclinic Docker Image CI With Postgres

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{matrix.java}}
      uses: actions/setup-java@v2
      with:
        java-version: ${{matrix.java}}
        distribution: 'adopt'
        cache: maven

    - name: Build Spring PetClinic
      run: |
        cp target/*.jar $GITHUB_WORKSPACE
      working-directory: ${{ github.workspace }}

    - name: Run Spring PetClinic
      run: |
        cd $GITHUB_WORKSPACE
        java -jar spring-petclinic-3.1.0-SNAPSHOT.jar --spring.profiles.active=postgres

    - name: Build docker file   
      run: docker build . --file Dockerfile --tag petclinic_postgres:$(date +%s)
