name: Build Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  name: Build Docker Image
  BuildDockerImage:
    needs: Build Petclinic App
    runs-on: ubuntu-latest

    steps:
      - name: Dependant is Running
        run: |
          echo "Completed job 2, but triggering failure"
          exit 1

      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

